### ISSUE TITLE
GPLv3 is not a valid license for Minecraft mods

### ISSUE THREAD

**Issue by unilock** [Wurst-Imperium/ChestESP#2]
[GPLv3](https://choosealicense.com/licenses/gpl-3.0/) cannot be used for Minecraft mods, as it requires all dependencies of the mod to also be licensed under GPL, of which Minecraft is not.

More info: https://github.com/modrinth/knossos/issues/258

The "next best" license would likely be [LGPLv3](https://choosealicense.com/licenses/lgpl-3.0/), as:
> The main difference between the GPL and the LGPL is that the latter allows the work to be linked with (in the case of a library, "used by") a non-(L)GPLed program, regardless of whether it is licensed under a license of GPL family or other licenses.
> *\- [Wikipedia](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#Differences_from_the_GPL)*

(I am not a lawyer, of course, but I'm pretty sure about this one)

**Comment by Alexander01998** [comment]
Hey @unilock! Thanks for your comment, but there seems to be a bit of a misunderstanding about the licensing requirements for Minecraft mods.

The GPLv3 license can indeed be used for Minecraft mods. It doesn't require all _dependencies_ to be licensed under GPL, but all _dependents_. If you look closely at that Wikipedia quote, that's actually what it's saying. You just got it backwards.

The idea of the GPL is that if you fork the mod and build upon it, you have to share those improvements with the open source community. Nobody can just take the code and turn it into something proprietary, hiding the source code to gain an advantage over the competition. The license protects us against that.

Besides, the word "dependency", in this context, doesn't mean what you think it does. ChestESP doesn't contain Minecraft's source code, as Mojang would try to take the mod down if it did. Both Fabric and Forge have systems in place to ensure that we as modders never actually distribute Minecraft's code. So Minecraft is not a dependency in that sense.

It can be helpful to think of Minecraft mods as [plugins for a non-free program](https://opensource.stackexchange.com/questions/8014/can-i-gpl-licence-a-plugin-for-a-non-free-program). They are self-contained and cleanly separated from the non-free program's code. Using them on a computer that happens to also run some proprietary software is not an issue - it's considered private use under the GPL.

I hope this clears things up! If you have any further questions or concerns, feel free to let me know.

**Comment by Alexander01998** [comment]
@unilock I really don't know why you felt the need to come back to this issue a year later and repeat a bunch of misinformation that I've already told you is wrong and that even your own sources clearly disagree with. You said in your original comment that you are not a lawyer, so maybe leave this one to those of us who have actually researched this topic instead of harassing random mod developers. Enough is enough.
