### ISSUE TITLE
IT IS BUGGY AND GLITCHES

### ISSUE THREAD

**Issue by bentleycpvp** [Wurst-Imperium/ChestESP#4]

**Comment by Alexander01998** [comment]
Hi @bentleycpvp,

I understand your frustration, but please keep in mind that vague caps-lock posting doesn't lead to your issue actually getting resolved. Right now, nobody even knows what bugs and/or glitches you are referring to.

Instead, let's work towards identifying and resolving the problem:
- Please explain the bugs and glitches you're experiencing in as much detail as possible.
- If you have any error messages, crash report files, or screenshots of glitchy behavior, please share those too.
- Lastly, if you can figure out the specific steps to reproduce the bugs or glitches, that would be super helpful.

The more information you can share, the quicker we can track down the problem and get it sorted.
